### ISSUE TITLE
Support for older hardware eg. Ledger Nano

### ISSUE THREAD

**Issue by HamishMacEwan** [bitcoin-core/HWI#168]
When I saw Core was entering this area I hoped older devices like the Ledger Nano (no S) might be included?

**Comment by achow101** [comment]
Unfortunately none of us who work on this project have access to every single hardware wallet ever (including the Ledger Nano) so we can't add support for devices which we do not have. However, if you do have those devices, feel free to implement support for them and open a pull request to add it. Otherwise you will need to wait for someone else to implement them or for one of us to acquire those devices.
