### ISSUE TITLE
is timestamp: now correct?

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#173]
I was reading throught the code for importmulti, it seems that `timestamp: "now"` starts scanning at the latest block? so rescans effectively don't happen? should timestamp be 0 or configurable?

**Comment by achow101** [comment]
Yes, that was intentional. It's so that the import is fast. Using `timestamp: 0` would result in having to wait hours for the rescan to work. I find this to be more user friendly as if a rescan were necessary (i.e. the HW was not new), then one can be triggered by using `rescanblockchain`.

Ideally the timestamp should be configurable based on some command line parameter.
