### ISSUE TITLE
coldcard: password is ignored

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#225]
Seems like this is related to #199 ?

when I type: 

```
hwi --stdinpass --device-type coldcard --device-path 0001:0008:00 displayaddress --path "m/84'/0'/0'/0/0" --wpkh
```

I get the same address no matter what password I give.

**Comment by achow101** [comment]
password on coldcard is not supported. While the coldcard supports taking the password over USB, we don't do that because it is a "register password for use in this session" type of thing. The Trezor One allows us the reset the session at will which allows for the different passwords for every command; Coldcard does not do this so the password over USB is not supported. Instead enter your password on the device itself.

You will observe the same behavior if you use password with the Trezor T and enter the password on device.
