### ISSUE TITLE
KeepKey detected by `enumerate` when Trezor plugged in

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/HWI#230]
```
$ hwi enumerate
[{'code': -13,
  'error': 'Could not open client or get fingerprint information: '
           'LIBUSB_ERROR_BUSY [-6]',
  'path': 'webusb:001:1',
  'type': 'trezor'},
 {'code': -14,
  'error': 'Could not open client or get fingerprint information: '
           'get_pubkey_at_path canceled',
  'path': '0003:0016:00',
  'type': 'ledger'},
 {'code': -13,
  'error': 'Could not open client or get fingerprint information: '
           'LIBUSB_ERROR_BUSY [-6]',
  'path': 'webusb:001:1',
  'type': 'keepkey'}]
```

I have a Trezor One and a Ledger Nano-S plugged in. Just prompted a pin for the Trezor just before this from python and that `TrezorClient` instance was still active. No KeepKey has ever been plugged into my machine.

**Comment by achow101** [comment]
I think this is unavoidable. Both Trezor and Keepkey use the same wire protocol (the Keepkey is a clone of the Trezor) and do almost everything identically. The only way to distinguish them is to wait for the device to respond to and check what vendor and device information it reports. In this case, because the Trezor is not responding to normal messages as it is in a special mode for PIN entry, HWI cannot tell whether it is a Trezor or if it is a Keepkey.
