### ISSUE TITLE
Build with ubuntu-20.04 rather than ubuntu-latest

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#732]
The currently released 3.0.0 Linux binaries fail on Ubuntu 20.04 with `version 'GLIBC_2.35' not found`. 

There seems to be no particular reason to require Ubuntu 22.04 or later, and this could be fixed by changing the relevant `runs-on` parameter in `workflow.yml` from `ubuntu-latest` to `ubuntu-20.04`.

**Comment by achow101** [comment]
The release binaries use https://github.com/bitcoin-core/HWI/blob/master/contrib/build.Dockerfile and is separate from the github actions workflows. It uses debian bookworm, which is also fairly recent.

IIRC this was done because something stopped working with the previous target of oldoldstable, and every version in between, although I no longer remember what.

**Comment by molnard** [comment]
With the default installation, `hwi` won't work on `20.04`. As a result, all who are using Wasabi with hardware wallets must have `Ubuntu 22.04`+ or update `GLIBC`. Is it possible to have a release that is working on `ubuntu-20.04`?
